// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimulationItemProto.proto

package controller.Proto;

public final class SimulationItemProto {
  private SimulationItemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimulationItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:controller.Proto.SimulationItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
     */
    controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType getType();
  }
  /**
   * Protobuf type {@code controller.Proto.SimulationItem}
   */
  public static final class SimulationItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:controller.Proto.SimulationItem)
      SimulationItemOrBuilder {
    // Use SimulationItem.newBuilder() to construct.
    private SimulationItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimulationItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimulationItem defaultInstance;
    public static SimulationItem getDefaultInstance() {
      return defaultInstance;
    }

    public SimulationItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimulationItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType value = controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return controller.Proto.SimulationItemProto.internal_static_controller_SimulationItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return controller.Proto.SimulationItemProto.internal_static_controller_SimulationItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              controller.Proto.SimulationItemProto.SimulationItem.class, controller.Proto.SimulationItemProto.SimulationItem.Builder.class);
    }

    public static com.google.protobuf.Parser<SimulationItem> PARSER =
        new com.google.protobuf.AbstractParser<SimulationItem>() {
      public SimulationItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimulationItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimulationItem> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code controller.Proto.SimulationItem.SimulationItemType}
     */
    public enum SimulationItemType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CRANE = 0;</code>
       */
      CRANE(0, 0),
      /**
       * <code>PLATFORM = 1;</code>
       */
      PLATFORM(1, 1),
      ;

      /**
       * <code>CRANE = 0;</code>
       */
      public static final int CRANE_VALUE = 0;
      /**
       * <code>PLATFORM = 1;</code>
       */
      public static final int PLATFORM_VALUE = 1;


      public final int getNumber() { return value; }

      public static SimulationItemType valueOf(int value) {
        switch (value) {
          case 0: return CRANE;
          case 1: return PLATFORM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>() {
              public SimulationItemType findValueByNumber(int number) {
                return SimulationItemType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return controller.Proto.SimulationItemProto.SimulationItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final SimulationItemType[] VALUES = values();

      public static SimulationItemType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SimulationItemType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:controller.Proto.SimulationItem.SimulationItemType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType type_;
    /**
     * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
     */
    public controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType getType() {
      return type_;
    }

    private void initFields() {
      id_ = "";
      type_ = controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType.CRANE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static controller.Proto.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(controller.Proto.SimulationItemProto.SimulationItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code controller.Proto.SimulationItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:controller.Proto.SimulationItem)
        controller.Proto.SimulationItemProto.SimulationItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return controller.Proto.SimulationItemProto.internal_static_controller_SimulationItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return controller.Proto.SimulationItemProto.internal_static_controller_SimulationItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                controller.Proto.SimulationItemProto.SimulationItem.class, controller.Proto.SimulationItemProto.SimulationItem.Builder.class);
      }

      // Construct using controller.Proto.SimulationItemProto.SimulationItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType.CRANE;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return controller.Proto.SimulationItemProto.internal_static_controller_SimulationItem_descriptor;
      }

      public controller.Proto.SimulationItemProto.SimulationItem getDefaultInstanceForType() {
        return controller.Proto.SimulationItemProto.SimulationItem.getDefaultInstance();
      }

      public controller.Proto.SimulationItemProto.SimulationItem build() {
        controller.Proto.SimulationItemProto.SimulationItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public controller.Proto.SimulationItemProto.SimulationItem buildPartial() {
        controller.Proto.SimulationItemProto.SimulationItem result = new controller.Proto.SimulationItemProto.SimulationItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof controller.Proto.SimulationItemProto.SimulationItem) {
          return mergeFrom((controller.Proto.SimulationItemProto.SimulationItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(controller.Proto.SimulationItemProto.SimulationItem other) {
        if (other == controller.Proto.SimulationItemProto.SimulationItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        controller.Proto.SimulationItemProto.SimulationItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (controller.Proto.SimulationItemProto.SimulationItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType type_ = controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType.CRANE;
      /**
       * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
       */
      public controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType getType() {
        return type_;
      }
      /**
       * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
       */
      public Builder setType(controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .controller.Proto.SimulationItem.SimulationItemType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = controller.Proto.SimulationItemProto.SimulationItem.SimulationItemType.CRANE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:controller.Proto.SimulationItem)
    }

    static {
      defaultInstance = new SimulationItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:controller.Proto.SimulationItem)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_controller_SimulationItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_controller_SimulationItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SimulationItemProto.proto\022\ncontroller\"" +
      "\210\001\n\016SimulationItem\022\n\n\002id\030\001 \002(\t\022;\n\004type\030\002" +
      " \002(\0162-.controller.Proto.SimulationItem.Simulat" +
      "ionItemType\"-\n\022SimulationItemType\022\t\n\005CRA" +
      "NE\020\000\022\014\n\010PLATFORM\020\001B\025B\023SimulationItemProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_controller_SimulationItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_controller_SimulationItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_controller_SimulationItem_descriptor,
        new java.lang.String[] { "Id", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
