// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile.proto

package nhl.containing.managmentinterface.data;

public final class ContainerProtos {
  private ContainerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code data.ContainerCategory}
   */
  public enum ContainerCategory
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRAIN = 0;</code>
     */
    TRAIN(0, 0),
    /**
     * <code>TRUCK = 1;</code>
     */
    TRUCK(1, 1),
    /**
     * <code>SEASHIP = 2;</code>
     */
    SEASHIP(2, 2),
    /**
     * <code>INLINESHIP = 3;</code>
     */
    INLINESHIP(3, 3),
    /**
     * <code>STORAGE = 4;</code>
     */
    STORAGE(4, 4),
    /**
     * <code>AGV = 5;</code>
     */
    AGV(5, 5),
    /**
     * <code>REMAINDER = 6;</code>
     */
    REMAINDER(6, 6),
    ;

    /**
     * <code>TRAIN = 0;</code>
     */
    public static final int TRAIN_VALUE = 0;
    /**
     * <code>TRUCK = 1;</code>
     */
    public static final int TRUCK_VALUE = 1;
    /**
     * <code>SEASHIP = 2;</code>
     */
    public static final int SEASHIP_VALUE = 2;
    /**
     * <code>INLINESHIP = 3;</code>
     */
    public static final int INLINESHIP_VALUE = 3;
    /**
     * <code>STORAGE = 4;</code>
     */
    public static final int STORAGE_VALUE = 4;
    /**
     * <code>AGV = 5;</code>
     */
    public static final int AGV_VALUE = 5;
    /**
     * <code>REMAINDER = 6;</code>
     */
    public static final int REMAINDER_VALUE = 6;


    public final int getNumber() { return value; }

    public static ContainerCategory valueOf(int value) {
      switch (value) {
        case 0: return TRAIN;
        case 1: return TRUCK;
        case 2: return SEASHIP;
        case 3: return INLINESHIP;
        case 4: return STORAGE;
        case 5: return AGV;
        case 6: return REMAINDER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContainerCategory>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ContainerCategory>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContainerCategory>() {
            public ContainerCategory findValueByNumber(int number) {
              return ContainerCategory.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nhl.containing.managmentinterface.data.ContainerProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final ContainerCategory[] VALUES = values();

    public static ContainerCategory valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ContainerCategory(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:data.ContainerCategory)
  }

  public interface ContainerDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.ContainerData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .data.ContainerCategory category = 1;</code>
     */
    boolean hasCategory();
    /**
     * <code>required .data.ContainerCategory category = 1;</code>
     */
    nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory getCategory();

    /**
     * <code>required int32 aantal = 2;</code>
     */
    boolean hasAantal();
    /**
     * <code>required int32 aantal = 2;</code>
     */
    int getAantal();
  }
  /**
   * Protobuf type {@code data.ContainerData}
   */
  public static final class ContainerData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.ContainerData)
      ContainerDataOrBuilder {
    // Use ContainerData.newBuilder() to construct.
    private ContainerData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ContainerData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ContainerData defaultInstance;
    public static ContainerData getDefaultInstance() {
      return defaultInstance;
    }

    public ContainerData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ContainerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory value = nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                category_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              aantal_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.class, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder.class);
    }

    public static com.google.protobuf.Parser<ContainerData> PARSER =
        new com.google.protobuf.AbstractParser<ContainerData>() {
      public ContainerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContainerData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ContainerData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CATEGORY_FIELD_NUMBER = 1;
    private nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory category_;
    /**
     * <code>required .data.ContainerCategory category = 1;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .data.ContainerCategory category = 1;</code>
     */
    public nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory getCategory() {
      return category_;
    }

    public static final int AANTAL_FIELD_NUMBER = 2;
    private int aantal_;
    /**
     * <code>required int32 aantal = 2;</code>
     */
    public boolean hasAantal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 aantal = 2;</code>
     */
    public int getAantal() {
      return aantal_;
    }

    private void initFields() {
      category_ = nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory.TRAIN;
      aantal_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAantal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, category_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, aantal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, category_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, aantal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.managmentinterface.data.ContainerProtos.ContainerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.ContainerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.ContainerData)
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.class, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder.class);
      }

      // Construct using nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        category_ = nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory.TRAIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        aantal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerData_descriptor;
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData getDefaultInstanceForType() {
        return nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.getDefaultInstance();
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData build() {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData buildPartial() {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerData result = new nhl.containing.managmentinterface.data.ContainerProtos.ContainerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.aantal_ = aantal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.managmentinterface.data.ContainerProtos.ContainerData) {
          return mergeFrom((nhl.containing.managmentinterface.data.ContainerProtos.ContainerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.managmentinterface.data.ContainerProtos.ContainerData other) {
        if (other == nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasAantal()) {
          setAantal(other.getAantal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCategory()) {
          
          return false;
        }
        if (!hasAantal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.managmentinterface.data.ContainerProtos.ContainerData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory category_ = nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory.TRAIN;
      /**
       * <code>required .data.ContainerCategory category = 1;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .data.ContainerCategory category = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory getCategory() {
        return category_;
      }
      /**
       * <code>required .data.ContainerCategory category = 1;</code>
       */
      public Builder setCategory(nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .data.ContainerCategory category = 1;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = nhl.containing.managmentinterface.data.ContainerProtos.ContainerCategory.TRAIN;
        onChanged();
        return this;
      }

      private int aantal_ ;
      /**
       * <code>required int32 aantal = 2;</code>
       */
      public boolean hasAantal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 aantal = 2;</code>
       */
      public int getAantal() {
        return aantal_;
      }
      /**
       * <code>required int32 aantal = 2;</code>
       */
      public Builder setAantal(int value) {
        bitField0_ |= 0x00000002;
        aantal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 aantal = 2;</code>
       */
      public Builder clearAantal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        aantal_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:data.ContainerData)
    }

    static {
      defaultInstance = new ContainerData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data.ContainerData)
  }

  public interface ContainerListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.ContainerList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> 
        getContainersList();
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    nhl.containing.managmentinterface.data.ContainerProtos.ContainerData getContainers(int index);
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    int getContainersCount();
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    java.util.List<? extends nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder> 
        getContainersOrBuilderList();
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder getContainersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code data.ContainerList}
   */
  public static final class ContainerList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.ContainerList)
      ContainerListOrBuilder {
    // Use ContainerList.newBuilder() to construct.
    private ContainerList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ContainerList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ContainerList defaultInstance;
    public static ContainerList getDefaultInstance() {
      return defaultInstance;
    }

    public ContainerList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ContainerList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                containers_ = new java.util.ArrayList<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData>();
                mutable_bitField0_ |= 0x00000001;
              }
              containers_.add(input.readMessage(nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          containers_ = java.util.Collections.unmodifiableList(containers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.class, nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.Builder.class);
    }

    public static com.google.protobuf.Parser<ContainerList> PARSER =
        new com.google.protobuf.AbstractParser<ContainerList>() {
      public ContainerList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContainerList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ContainerList> getParserForType() {
      return PARSER;
    }

    public static final int CONTAINERS_FIELD_NUMBER = 1;
    private java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> containers_;
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    public java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> getContainersList() {
      return containers_;
    }
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    public java.util.List<? extends nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder> 
        getContainersOrBuilderList() {
      return containers_;
    }
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    public int getContainersCount() {
      return containers_.size();
    }
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData getContainers(int index) {
      return containers_.get(index);
    }
    /**
     * <code>repeated .data.ContainerData containers = 1;</code>
     */
    public nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder getContainersOrBuilder(
        int index) {
      return containers_.get(index);
    }

    private void initFields() {
      containers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getContainersCount(); i++) {
        if (!getContainers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < containers_.size(); i++) {
        output.writeMessage(1, containers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < containers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, containers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.managmentinterface.data.ContainerProtos.ContainerList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.ContainerList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.ContainerList)
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.class, nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.Builder.class);
      }

      // Construct using nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContainersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (containersBuilder_ == null) {
          containers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          containersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.managmentinterface.data.ContainerProtos.internal_static_data_ContainerList_descriptor;
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerList getDefaultInstanceForType() {
        return nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.getDefaultInstance();
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerList build() {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerList buildPartial() {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerList result = new nhl.containing.managmentinterface.data.ContainerProtos.ContainerList(this);
        int from_bitField0_ = bitField0_;
        if (containersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            containers_ = java.util.Collections.unmodifiableList(containers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.containers_ = containers_;
        } else {
          result.containers_ = containersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.managmentinterface.data.ContainerProtos.ContainerList) {
          return mergeFrom((nhl.containing.managmentinterface.data.ContainerProtos.ContainerList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.managmentinterface.data.ContainerProtos.ContainerList other) {
        if (other == nhl.containing.managmentinterface.data.ContainerProtos.ContainerList.getDefaultInstance()) return this;
        if (containersBuilder_ == null) {
          if (!other.containers_.isEmpty()) {
            if (containers_.isEmpty()) {
              containers_ = other.containers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContainersIsMutable();
              containers_.addAll(other.containers_);
            }
            onChanged();
          }
        } else {
          if (!other.containers_.isEmpty()) {
            if (containersBuilder_.isEmpty()) {
              containersBuilder_.dispose();
              containersBuilder_ = null;
              containers_ = other.containers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              containersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContainersFieldBuilder() : null;
            } else {
              containersBuilder_.addAllMessages(other.containers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getContainersCount(); i++) {
          if (!getContainers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.managmentinterface.data.ContainerProtos.ContainerList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.managmentinterface.data.ContainerProtos.ContainerList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> containers_ =
        java.util.Collections.emptyList();
      private void ensureContainersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          containers_ = new java.util.ArrayList<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData>(containers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.managmentinterface.data.ContainerProtos.ContainerData, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder, nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder> containersBuilder_;

      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> getContainersList() {
        if (containersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(containers_);
        } else {
          return containersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public int getContainersCount() {
        if (containersBuilder_ == null) {
          return containers_.size();
        } else {
          return containersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData getContainers(int index) {
        if (containersBuilder_ == null) {
          return containers_.get(index);
        } else {
          return containersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder setContainers(
          int index, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData value) {
        if (containersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContainersIsMutable();
          containers_.set(index, value);
          onChanged();
        } else {
          containersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder setContainers(
          int index, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder builderForValue) {
        if (containersBuilder_ == null) {
          ensureContainersIsMutable();
          containers_.set(index, builderForValue.build());
          onChanged();
        } else {
          containersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder addContainers(nhl.containing.managmentinterface.data.ContainerProtos.ContainerData value) {
        if (containersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContainersIsMutable();
          containers_.add(value);
          onChanged();
        } else {
          containersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder addContainers(
          int index, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData value) {
        if (containersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContainersIsMutable();
          containers_.add(index, value);
          onChanged();
        } else {
          containersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder addContainers(
          nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder builderForValue) {
        if (containersBuilder_ == null) {
          ensureContainersIsMutable();
          containers_.add(builderForValue.build());
          onChanged();
        } else {
          containersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder addContainers(
          int index, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder builderForValue) {
        if (containersBuilder_ == null) {
          ensureContainersIsMutable();
          containers_.add(index, builderForValue.build());
          onChanged();
        } else {
          containersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder addAllContainers(
          java.lang.Iterable<? extends nhl.containing.managmentinterface.data.ContainerProtos.ContainerData> values) {
        if (containersBuilder_ == null) {
          ensureContainersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, containers_);
          onChanged();
        } else {
          containersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder clearContainers() {
        if (containersBuilder_ == null) {
          containers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          containersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public Builder removeContainers(int index) {
        if (containersBuilder_ == null) {
          ensureContainersIsMutable();
          containers_.remove(index);
          onChanged();
        } else {
          containersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder getContainersBuilder(
          int index) {
        return getContainersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder getContainersOrBuilder(
          int index) {
        if (containersBuilder_ == null) {
          return containers_.get(index);  } else {
          return containersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public java.util.List<? extends nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder> 
           getContainersOrBuilderList() {
        if (containersBuilder_ != null) {
          return containersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(containers_);
        }
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder addContainersBuilder() {
        return getContainersFieldBuilder().addBuilder(
            nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.getDefaultInstance());
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder addContainersBuilder(
          int index) {
        return getContainersFieldBuilder().addBuilder(
            index, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.getDefaultInstance());
      }
      /**
       * <code>repeated .data.ContainerData containers = 1;</code>
       */
      public java.util.List<nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder> 
           getContainersBuilderList() {
        return getContainersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.managmentinterface.data.ContainerProtos.ContainerData, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder, nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder> 
          getContainersFieldBuilder() {
        if (containersBuilder_ == null) {
          containersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              nhl.containing.managmentinterface.data.ContainerProtos.ContainerData, nhl.containing.managmentinterface.data.ContainerProtos.ContainerData.Builder, nhl.containing.managmentinterface.data.ContainerProtos.ContainerDataOrBuilder>(
                  containers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          containers_ = null;
        }
        return containersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:data.ContainerList)
    }

    static {
      defaultInstance = new ContainerList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data.ContainerList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ContainerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_ContainerData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ContainerList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_ContainerList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017protofile.proto\022\004data\"J\n\rContainerData" +
      "\022)\n\010category\030\001 \002(\0162\027.data.ContainerCateg" +
      "ory\022\016\n\006aantal\030\002 \002(\005\"8\n\rContainerList\022\'\n\n" +
      "containers\030\001 \003(\0132\023.data.ContainerData*k\n" +
      "\021ContainerCategory\022\t\n\005TRAIN\020\000\022\t\n\005TRUCK\020\001" +
      "\022\013\n\007SEASHIP\020\002\022\016\n\nINLINESHIP\020\003\022\013\n\007STORAGE" +
      "\020\004\022\007\n\003AGV\020\005\022\r\n\tREMAINDER\020\006B9\n&nhl.contai" +
      "ning.managmentinterface.dataB\017ContainerP" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_ContainerData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_ContainerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_ContainerData_descriptor,
        new java.lang.String[] { "Category", "Aantal", });
    internal_static_data_ContainerList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_ContainerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_ContainerList_descriptor,
        new java.lang.String[] { "Containers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
