/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_JNITest */

#ifndef _Included_controller_JNITest
#define _Included_controller_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_JNITest
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_helloFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
