// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientIdProto.proto

package nhl.containing.networking.protobuf;

public final class ClientIdProto {
  private ClientIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientIdentityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;
    /**
     * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
     */
    boolean hasClientType();
    /**
     * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
     */
    nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType getClientType();

    // optional int32 version = 2;
    /**
     * <code>optional int32 version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 2;</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code nhl.containing.networking.protobuf.ClientIdentity}
   */
  public static final class ClientIdentity extends
      com.google.protobuf.GeneratedMessage
      implements ClientIdentityOrBuilder {
    // Use ClientIdentity.newBuilder() to construct.
    private ClientIdentity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientIdentity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientIdentity defaultInstance;
    public static ClientIdentity getDefaultInstance() {
      return defaultInstance;
    }

    public ClientIdentity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientIdentity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType value = nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                clientType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.networking.protobuf.ClientIdProto.internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.networking.protobuf.ClientIdProto.internal_static_nhl_containing_networking_protobuf_ClientIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.class, nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientIdentity> PARSER =
        new com.google.protobuf.AbstractParser<ClientIdentity>() {
      public ClientIdentity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientIdentity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientIdentity> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code nhl.containing.networking.protobuf.ClientIdentity.ClientType}
     */
    public enum ClientType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SIMULATOR = 1;</code>
       */
      SIMULATOR(0, 1),
      /**
       * <code>APP = 2;</code>
       */
      APP(1, 2),
      ;

      /**
       * <code>SIMULATOR = 1;</code>
       */
      public static final int SIMULATOR_VALUE = 1;
      /**
       * <code>APP = 2;</code>
       */
      public static final int APP_VALUE = 2;


      public final int getNumber() { return value; }

      public static ClientType valueOf(int value) {
        switch (value) {
          case 1: return SIMULATOR;
          case 2: return APP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ClientType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
              public ClientType findValueByNumber(int number) {
                return ClientType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientType[] VALUES = values();

      public static ClientType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ClientType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:nhl.containing.networking.protobuf.ClientIdentity.ClientType)
    }

    private int bitField0_;
    // required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;
    public static final int CLIENTTYPE_FIELD_NUMBER = 1;
    private nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType clientType_;
    /**
     * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
     */
    public boolean hasClientType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
     */
    public nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType getClientType() {
      return clientType_;
    }

    // optional int32 version = 2;
    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>optional int32 version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    private void initFields() {
      clientType_ = nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType.SIMULATOR;
      version_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClientType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, clientType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, version_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, clientType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nhl.containing.networking.protobuf.ClientIdentity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nhl.containing.networking.protobuf.ClientIdProto.ClientIdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.ClientIdProto.internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.networking.protobuf.ClientIdProto.internal_static_nhl_containing_networking_protobuf_ClientIdentity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.class, nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.Builder.class);
      }

      // Construct using nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientType_ = nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType.SIMULATOR;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.networking.protobuf.ClientIdProto.internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor;
      }

      public nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity getDefaultInstanceForType() {
        return nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.getDefaultInstance();
      }

      public nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity build() {
        nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity buildPartial() {
        nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity result = new nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientType_ = clientType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity) {
          return mergeFrom((nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity other) {
        if (other == nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.getDefaultInstance()) return this;
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;
      private nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType clientType_ = nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType.SIMULATOR;
      /**
       * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
       */
      public boolean hasClientType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
       */
      public nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType getClientType() {
        return clientType_;
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
       */
      public Builder setClientType(nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        clientType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.ClientIdentity.ClientType clientType = 1;</code>
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientType_ = nhl.containing.networking.protobuf.ClientIdProto.ClientIdentity.ClientType.SIMULATOR;
        onChanged();
        return this;
      }

      // optional int32 version = 2;
      private int version_ ;
      /**
       * <code>optional int32 version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:nhl.containing.networking.protobuf.ClientIdentity)
    }

    static {
      defaultInstance = new ClientIdentity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nhl.containing.networking.protobuf.ClientIdentity)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nhl_containing_networking_protobuf_ClientIdentity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientIdProto.proto\022\"nhl.containing.ne" +
      "tworking.protobuf\"\232\001\n\016ClientIdentity\022Q\n\n" +
      "clientType\030\001 \002(\0162=.nhl.containing.networ" +
      "king.protobuf.ClientIdentity.ClientType\022" +
      "\017\n\007version\030\002 \001(\005\"$\n\nClientType\022\r\n\tSIMULA" +
      "TOR\020\001\022\007\n\003APP\020\002B\017B\rClientIdProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nhl_containing_networking_protobuf_ClientIdentity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nhl_containing_networking_protobuf_ClientIdentity_descriptor,
              new java.lang.String[] { "ClientType", "Version", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
