// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: networking/Proto/Platform.proto

package nhl.containing.networking.protobuf;

public final class PlatformProto {
  private PlatformProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlatformOrBuilder extends
      // @@protoc_insertion_point(interface_extends:networking.Proto.Platform)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
     */
    nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType getType();

    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> 
        getCranesList();
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    nhl.containing.networking.protobuf.PlatformProto.Platform.Crane getCranes(int index);
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    int getCranesCount();
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    java.util.List<? extends nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder> 
        getCranesOrBuilderList();
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder getCranesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code networking.Proto.Platform}
   */
  public static final class Platform extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:networking.Proto.Platform)
      PlatformOrBuilder {
    // Use Platform.newBuilder() to construct.
    private Platform(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Platform(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Platform defaultInstance;
    public static Platform getDefaultInstance() {
      return defaultInstance;
    }

    public Platform getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Platform(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType value = nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                cranes_ = new java.util.ArrayList<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane>();
                mutable_bitField0_ |= 0x00000004;
              }
              cranes_.add(input.readMessage(nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          cranes_ = java.util.Collections.unmodifiableList(cranes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.networking.protobuf.PlatformProto.Platform.class, nhl.containing.networking.protobuf.PlatformProto.Platform.Builder.class);
    }

    public static com.google.protobuf.Parser<Platform> PARSER =
        new com.google.protobuf.AbstractParser<Platform>() {
      public Platform parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Platform(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Platform> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code networking.Proto.Platform.PlatformType}
     */
    public enum PlatformType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SeaShip = 0;</code>
       */
      SeaShip(0, 0),
      /**
       * <code>InlandShip = 1;</code>
       */
      InlandShip(1, 1),
      /**
       * <code>Truck = 2;</code>
       */
      Truck(2, 2),
      /**
       * <code>Train = 3;</code>
       */
      Train(3, 3),
      /**
       * <code>Deposit = 4;</code>
       */
      Deposit(4, 4),
      ;

      /**
       * <code>SeaShip = 0;</code>
       */
      public static final int SeaShip_VALUE = 0;
      /**
       * <code>InlandShip = 1;</code>
       */
      public static final int InlandShip_VALUE = 1;
      /**
       * <code>Truck = 2;</code>
       */
      public static final int Truck_VALUE = 2;
      /**
       * <code>Train = 3;</code>
       */
      public static final int Train_VALUE = 3;
      /**
       * <code>Deposit = 4;</code>
       */
      public static final int Deposit_VALUE = 4;


      public final int getNumber() { return value; }

      public static PlatformType valueOf(int value) {
        switch (value) {
          case 0: return SeaShip;
          case 1: return InlandShip;
          case 2: return Truck;
          case 3: return Train;
          case 4: return Deposit;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
              public PlatformType findValueByNumber(int number) {
                return PlatformType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.PlatformProto.Platform.getDescriptor().getEnumTypes().get(0);
      }

      private static final PlatformType[] VALUES = values();

      public static PlatformType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PlatformType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:networking.Proto.Platform.PlatformType)
    }

    public interface CraneOrBuilder extends
        // @@protoc_insertion_point(interface_extends:networking.Proto.Platform.Crane)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>required string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
       */
      nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType getType();
    }
    /**
     * Protobuf type {@code networking.Proto.Platform.Crane}
     */
    public static final class Crane extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:networking.Proto.Platform.Crane)
        CraneOrBuilder {
      // Use Crane.newBuilder() to construct.
      private Crane(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Crane(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Crane defaultInstance;
      public static Crane getDefaultInstance() {
        return defaultInstance;
      }

      public Crane getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Crane(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                id_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType value = nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_Crane_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_Crane_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.class, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder.class);
      }

      public static com.google.protobuf.Parser<Crane> PARSER =
          new com.google.protobuf.AbstractParser<Crane>() {
        public Crane parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Crane(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Crane> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code networking.Proto.Platform.Crane.CraneType}
       */
      public enum CraneType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Rails = 0;</code>
         */
        Rails(0, 0),
        /**
         * <code>Free = 1;</code>
         */
        Free(1, 1),
        ;

        /**
         * <code>Rails = 0;</code>
         */
        public static final int Rails_VALUE = 0;
        /**
         * <code>Free = 1;</code>
         */
        public static final int Free_VALUE = 1;


        public final int getNumber() { return value; }

        public static CraneType valueOf(int value) {
          switch (value) {
            case 0: return Rails;
            case 1: return Free;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<CraneType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<CraneType>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<CraneType>() {
                public CraneType findValueByNumber(int number) {
                  return CraneType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.getDescriptor().getEnumTypes().get(0);
        }

        private static final CraneType[] VALUES = values();

        public static CraneType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private CraneType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:networking.Proto.Platform.Crane.CraneType)
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private java.lang.Object id_;
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType type_;
      /**
       * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType getType() {
        return type_;
      }

      private void initFields() {
        id_ = "";
        type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType.Rails;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(nhl.containing.networking.protobuf.PlatformProto.Platform.Crane prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code networking.Proto.Platform.Crane}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:networking.Proto.Platform.Crane)
          nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_Crane_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_Crane_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.class, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder.class);
        }

        // Construct using networking.Proto.PlatformProto.Platform.Crane.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType.Rails;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_Crane_descriptor;
        }

        public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane getDefaultInstanceForType() {
          return nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.getDefaultInstance();
        }

        public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane build() {
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane buildPartial() {
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane result = new nhl.containing.networking.protobuf.PlatformProto.Platform.Crane(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nhl.containing.networking.protobuf.PlatformProto.Platform.Crane) {
            return mergeFrom((nhl.containing.networking.protobuf.PlatformProto.Platform.Crane)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(nhl.containing.networking.protobuf.PlatformProto.Platform.Crane other) {
          if (other == nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.getDefaultInstance()) return this;
          if (other.hasId()) {
            bitField0_ |= 0x00000001;
            id_ = other.id_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (nhl.containing.networking.protobuf.PlatformProto.Platform.Crane) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object id_ = "";
        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              id_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }

        private nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType.Rails;
        /**
         * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
         */
        public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType getType() {
          return type_;
        }
        /**
         * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
         */
        public Builder setType(nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .networking.Proto.Platform.Crane.CraneType type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.CraneType.Rails;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:networking.Proto.Platform.Crane)
      }

      static {
        defaultInstance = new Crane(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:networking.Proto.Platform.Crane)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType type_;
    /**
     * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
     */
    public nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType getType() {
      return type_;
    }

    public static final int CRANES_FIELD_NUMBER = 3;
    private java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> cranes_;
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    public java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> getCranesList() {
      return cranes_;
    }
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    public java.util.List<? extends nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder> 
        getCranesOrBuilderList() {
      return cranes_;
    }
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    public int getCranesCount() {
      return cranes_.size();
    }
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane getCranes(int index) {
      return cranes_.get(index);
    }
    /**
     * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
     */
    public nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder getCranesOrBuilder(
        int index) {
      return cranes_.get(index);
    }

    private void initFields() {
      id_ = "";
      type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType.SeaShip;
      cranes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCranesCount(); i++) {
        if (!getCranes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      for (int i = 0; i < cranes_.size(); i++) {
        output.writeMessage(3, cranes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      for (int i = 0; i < cranes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, cranes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.PlatformProto.Platform parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.networking.protobuf.PlatformProto.Platform prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code networking.Proto.Platform}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:networking.Proto.Platform)
        nhl.containing.networking.protobuf.PlatformProto.PlatformOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.networking.protobuf.PlatformProto.Platform.class, nhl.containing.networking.protobuf.PlatformProto.Platform.Builder.class);
      }

      // Construct using networking.Proto.PlatformProto.Platform.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCranesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType.SeaShip;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (cranesBuilder_ == null) {
          cranes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          cranesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.networking.protobuf.PlatformProto.internal_static_networking_Proto_Platform_descriptor;
      }

      public nhl.containing.networking.protobuf.PlatformProto.Platform getDefaultInstanceForType() {
        return nhl.containing.networking.protobuf.PlatformProto.Platform.getDefaultInstance();
      }

      public nhl.containing.networking.protobuf.PlatformProto.Platform build() {
        nhl.containing.networking.protobuf.PlatformProto.Platform result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.networking.protobuf.PlatformProto.Platform buildPartial() {
        nhl.containing.networking.protobuf.PlatformProto.Platform result = new nhl.containing.networking.protobuf.PlatformProto.Platform(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (cranesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            cranes_ = java.util.Collections.unmodifiableList(cranes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.cranes_ = cranes_;
        } else {
          result.cranes_ = cranesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.networking.protobuf.PlatformProto.Platform) {
          return mergeFrom((nhl.containing.networking.protobuf.PlatformProto.Platform)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.networking.protobuf.PlatformProto.Platform other) {
        if (other == nhl.containing.networking.protobuf.PlatformProto.Platform.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (cranesBuilder_ == null) {
          if (!other.cranes_.isEmpty()) {
            if (cranes_.isEmpty()) {
              cranes_ = other.cranes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCranesIsMutable();
              cranes_.addAll(other.cranes_);
            }
            onChanged();
          }
        } else {
          if (!other.cranes_.isEmpty()) {
            if (cranesBuilder_.isEmpty()) {
              cranesBuilder_.dispose();
              cranesBuilder_ = null;
              cranes_ = other.cranes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              cranesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCranesFieldBuilder() : null;
            } else {
              cranesBuilder_.addAllMessages(other.cranes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getCranesCount(); i++) {
          if (!getCranes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.networking.protobuf.PlatformProto.Platform parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.networking.protobuf.PlatformProto.Platform) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType.SeaShip;
      /**
       * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType getType() {
        return type_;
      }
      /**
       * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
       */
      public Builder setType(nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .networking.Proto.Platform.PlatformType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = nhl.containing.networking.protobuf.PlatformProto.Platform.PlatformType.SeaShip;
        onChanged();
        return this;
      }

      private java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> cranes_ =
        java.util.Collections.emptyList();
      private void ensureCranesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          cranes_ = new java.util.ArrayList<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane>(cranes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder, nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder> cranesBuilder_;

      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> getCranesList() {
        if (cranesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cranes_);
        } else {
          return cranesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public int getCranesCount() {
        if (cranesBuilder_ == null) {
          return cranes_.size();
        } else {
          return cranesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane getCranes(int index) {
        if (cranesBuilder_ == null) {
          return cranes_.get(index);
        } else {
          return cranesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder setCranes(
          int index, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane value) {
        if (cranesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCranesIsMutable();
          cranes_.set(index, value);
          onChanged();
        } else {
          cranesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder setCranes(
          int index, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder builderForValue) {
        if (cranesBuilder_ == null) {
          ensureCranesIsMutable();
          cranes_.set(index, builderForValue.build());
          onChanged();
        } else {
          cranesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder addCranes(nhl.containing.networking.protobuf.PlatformProto.Platform.Crane value) {
        if (cranesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCranesIsMutable();
          cranes_.add(value);
          onChanged();
        } else {
          cranesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder addCranes(
          int index, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane value) {
        if (cranesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCranesIsMutable();
          cranes_.add(index, value);
          onChanged();
        } else {
          cranesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder addCranes(
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder builderForValue) {
        if (cranesBuilder_ == null) {
          ensureCranesIsMutable();
          cranes_.add(builderForValue.build());
          onChanged();
        } else {
          cranesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder addCranes(
          int index, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder builderForValue) {
        if (cranesBuilder_ == null) {
          ensureCranesIsMutable();
          cranes_.add(index, builderForValue.build());
          onChanged();
        } else {
          cranesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder addAllCranes(
          java.lang.Iterable<? extends nhl.containing.networking.protobuf.PlatformProto.Platform.Crane> values) {
        if (cranesBuilder_ == null) {
          ensureCranesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cranes_);
          onChanged();
        } else {
          cranesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder clearCranes() {
        if (cranesBuilder_ == null) {
          cranes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          cranesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public Builder removeCranes(int index) {
        if (cranesBuilder_ == null) {
          ensureCranesIsMutable();
          cranes_.remove(index);
          onChanged();
        } else {
          cranesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder getCranesBuilder(
          int index) {
        return getCranesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder getCranesOrBuilder(
          int index) {
        if (cranesBuilder_ == null) {
          return cranes_.get(index);  } else {
          return cranesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public java.util.List<? extends nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder> 
           getCranesOrBuilderList() {
        if (cranesBuilder_ != null) {
          return cranesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cranes_);
        }
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder addCranesBuilder() {
        return getCranesFieldBuilder().addBuilder(
            nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.getDefaultInstance());
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder addCranesBuilder(
          int index) {
        return getCranesFieldBuilder().addBuilder(
            index, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.getDefaultInstance());
      }
      /**
       * <code>repeated .networking.Proto.Platform.Crane cranes = 3;</code>
       */
      public java.util.List<nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder> 
           getCranesBuilderList() {
        return getCranesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.networking.protobuf.PlatformProto.Platform.Crane, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder, nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder> 
          getCranesFieldBuilder() {
        if (cranesBuilder_ == null) {
          cranesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              nhl.containing.networking.protobuf.PlatformProto.Platform.Crane, nhl.containing.networking.protobuf.PlatformProto.Platform.Crane.Builder, nhl.containing.networking.protobuf.PlatformProto.Platform.CraneOrBuilder>(
                  cranes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          cranes_ = null;
        }
        return cranesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:networking.Proto.Platform)
    }

    static {
      defaultInstance = new Platform(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:networking.Proto.Platform)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_networking_Proto_Platform_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_networking_Proto_Platform_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_networking_Proto_Platform_Crane_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_networking_Proto_Platform_Crane_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037networking/Proto/Platform.proto\022\020netwo" +
      "rking.Proto\"\300\002\n\010Platform\022\n\n\002id\030\001 \002(\t\0225\n\004" +
      "type\030\002 \002(\0162\'.networking.Proto.Platform.P" +
      "latformType\0220\n\006cranes\030\003 \003(\0132 .networking" +
      ".Proto.Platform.Crane\032o\n\005Crane\022\n\n\002id\030\001 \002" +
      "(\t\0228\n\004type\030\002 \002(\0162*.networking.Proto.Plat" +
      "form.Crane.CraneType\" \n\tCraneType\022\t\n\005Rai" +
      "ls\020\000\022\010\n\004Free\020\001\"N\n\014PlatformType\022\013\n\007SeaShi" +
      "p\020\000\022\016\n\nInlandShip\020\001\022\t\n\005Truck\020\002\022\t\n\005Train\020" +
      "\003\022\013\n\007Deposit\020\004B\017B\rPlatformProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_networking_Proto_Platform_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_networking_Proto_Platform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_networking_Proto_Platform_descriptor,
        new java.lang.String[] { "Id", "Type", "Cranes", });
    internal_static_networking_Proto_Platform_Crane_descriptor =
      internal_static_networking_Proto_Platform_descriptor.getNestedTypes().get(0);
    internal_static_networking_Proto_Platform_Crane_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_networking_Proto_Platform_Crane_descriptor,
        new java.lang.String[] { "Id", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
