// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimItemProto.proto

package nhl.containing.networking.protobuf;

public final class SimulationItemProto {
  private SimulationItemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimulationItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nhl.containing.networking.protobuf.SimulationItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
     */
    nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType getType();

    /**
     * <code>optional int32 parentID = 3;</code>
     */
    boolean hasParentID();
    /**
     * <code>optional int32 parentID = 3;</code>
     */
    int getParentID();

    /**
     * <code>optional float x = 4;</code>
     */
    boolean hasX();
    /**
     * <code>optional float x = 4;</code>
     */
    float getX();

    /**
     * <code>optional float y = 5;</code>
     */
    boolean hasY();
    /**
     * <code>optional float y = 5;</code>
     */
    float getY();

    /**
     * <code>optional float z = 6;</code>
     */
    boolean hasZ();
    /**
     * <code>optional float z = 6;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code nhl.containing.networking.protobuf.SimulationItem}
   */
  public static final class SimulationItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:nhl.containing.networking.protobuf.SimulationItem)
      SimulationItemOrBuilder {
    // Use SimulationItem.newBuilder() to construct.
    private SimulationItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimulationItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimulationItem defaultInstance;
    public static SimulationItem getDefaultInstance() {
      return defaultInstance;
    }

    public SimulationItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimulationItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType value = nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              parentID_ = input.readInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              x_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              y_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulationItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.class, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder.class);
    }

    public static com.google.protobuf.Parser<SimulationItem> PARSER =
        new com.google.protobuf.AbstractParser<SimulationItem>() {
      public SimulationItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimulationItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimulationItem> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code nhl.containing.networking.protobuf.SimulationItem.SimulationItemType}
     */
    public enum SimulationItemType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PLATFORM_STORAGE = 0;</code>
       */
      PLATFORM_STORAGE(0, 0),
      /**
       * <code>PARKINGSPOT_STORAGE = 1;</code>
       */
      PARKINGSPOT_STORAGE(1, 1),
      /**
       * <code>NODES = 2;</code>
       */
      NODES(2, 2),
      /**
       * <code>PLATFORM_TRAIN = 3;</code>
       */
      PLATFORM_TRAIN(3, 3),
      /**
       * <code>PLATFORM_SEASHIP = 4;</code>
       */
      PLATFORM_SEASHIP(4, 4),
      /**
       * <code>PLATFORM_INLANDSHIP = 5;</code>
       */
      PLATFORM_INLANDSHIP(5, 5),
      /**
       * <code>PLATFORM_LORRY = 6;</code>
       */
      PLATFORM_LORRY(6, 6),
      /**
       * <code>AGV = 7;</code>
       */
      AGV(7, 7),
      /**
       * <code>PARKINGSPOT_TRAIN = 8;</code>
       */
      PARKINGSPOT_TRAIN(8, 8),
      /**
       * <code>PARKINGSPOT_SEASHIP = 9;</code>
       */
      PARKINGSPOT_SEASHIP(9, 9),
      /**
       * <code>PARKINGSPOT_INLANDSHIP = 10;</code>
       */
      PARKINGSPOT_INLANDSHIP(10, 10),
      /**
       * <code>PARKINGSPOT_LORRY = 11;</code>
       */
      PARKINGSPOT_LORRY(11, 11),
      ;

      /**
       * <code>PLATFORM_STORAGE = 0;</code>
       */
      public static final int PLATFORM_STORAGE_VALUE = 0;
      /**
       * <code>PARKINGSPOT_STORAGE = 1;</code>
       */
      public static final int PARKINGSPOT_STORAGE_VALUE = 1;
      /**
       * <code>NODES = 2;</code>
       */
      public static final int NODES_VALUE = 2;
      /**
       * <code>PLATFORM_TRAIN = 3;</code>
       */
      public static final int PLATFORM_TRAIN_VALUE = 3;
      /**
       * <code>PLATFORM_SEASHIP = 4;</code>
       */
      public static final int PLATFORM_SEASHIP_VALUE = 4;
      /**
       * <code>PLATFORM_INLANDSHIP = 5;</code>
       */
      public static final int PLATFORM_INLANDSHIP_VALUE = 5;
      /**
       * <code>PLATFORM_LORRY = 6;</code>
       */
      public static final int PLATFORM_LORRY_VALUE = 6;
      /**
       * <code>AGV = 7;</code>
       */
      public static final int AGV_VALUE = 7;
      /**
       * <code>PARKINGSPOT_TRAIN = 8;</code>
       */
      public static final int PARKINGSPOT_TRAIN_VALUE = 8;
      /**
       * <code>PARKINGSPOT_SEASHIP = 9;</code>
       */
      public static final int PARKINGSPOT_SEASHIP_VALUE = 9;
      /**
       * <code>PARKINGSPOT_INLANDSHIP = 10;</code>
       */
      public static final int PARKINGSPOT_INLANDSHIP_VALUE = 10;
      /**
       * <code>PARKINGSPOT_LORRY = 11;</code>
       */
      public static final int PARKINGSPOT_LORRY_VALUE = 11;


      public final int getNumber() { return value; }

      public static SimulationItemType valueOf(int value) {
        switch (value) {
          case 0: return PLATFORM_STORAGE;
          case 1: return PARKINGSPOT_STORAGE;
          case 2: return NODES;
          case 3: return PLATFORM_TRAIN;
          case 4: return PLATFORM_SEASHIP;
          case 5: return PLATFORM_INLANDSHIP;
          case 6: return PLATFORM_LORRY;
          case 7: return AGV;
          case 8: return PARKINGSPOT_TRAIN;
          case 9: return PARKINGSPOT_SEASHIP;
          case 10: return PARKINGSPOT_INLANDSHIP;
          case 11: return PARKINGSPOT_LORRY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SimulationItemType>() {
              public SimulationItemType findValueByNumber(int number) {
                return SimulationItemType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final SimulationItemType[] VALUES = values();

      public static SimulationItemType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SimulationItemType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:nhl.containing.networking.protobuf.SimulationItem.SimulationItemType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType type_;
    /**
     * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
     */
    public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType getType() {
      return type_;
    }

    public static final int PARENTID_FIELD_NUMBER = 3;
    private int parentID_;
    /**
     * <code>optional int32 parentID = 3;</code>
     */
    public boolean hasParentID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 parentID = 3;</code>
     */
    public int getParentID() {
      return parentID_;
    }

    public static final int X_FIELD_NUMBER = 4;
    private float x_;
    /**
     * <code>optional float x = 4;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float x = 4;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 5;
    private float y_;
    /**
     * <code>optional float y = 5;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float y = 5;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 6;
    private float z_;
    /**
     * <code>optional float z = 6;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float z = 6;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      id_ = 0L;
      type_ = nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType.PLATFORM_STORAGE;
      parentID_ = 0;
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, parentID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, x_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, y_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, parentID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, x_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, y_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nhl.containing.networking.protobuf.SimulationItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nhl.containing.networking.protobuf.SimulationItem)
        nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulationItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.class, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder.class);
      }

      // Construct using nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType.PLATFORM_STORAGE;
        bitField0_ = (bitField0_ & ~0x00000002);
        parentID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor;
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem getDefaultInstanceForType() {
        return nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.getDefaultInstance();
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem build() {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem buildPartial() {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem result = new nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.parentID_ = parentID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem) {
          return mergeFrom((nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem other) {
        if (other == nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasParentID()) {
          setParentID(other.getParentID());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType type_ = nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType.PLATFORM_STORAGE;
      /**
       * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType getType() {
        return type_;
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
       */
      public Builder setType(nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .nhl.containing.networking.protobuf.SimulationItem.SimulationItemType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.SimulationItemType.PLATFORM_STORAGE;
        onChanged();
        return this;
      }

      private int parentID_ ;
      /**
       * <code>optional int32 parentID = 3;</code>
       */
      public boolean hasParentID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 parentID = 3;</code>
       */
      public int getParentID() {
        return parentID_;
      }
      /**
       * <code>optional int32 parentID = 3;</code>
       */
      public Builder setParentID(int value) {
        bitField0_ |= 0x00000004;
        parentID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 parentID = 3;</code>
       */
      public Builder clearParentID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parentID_ = 0;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>optional float x = 4;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float x = 4;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>optional float x = 4;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000008;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float x = 4;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>optional float y = 5;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float y = 5;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>optional float y = 5;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000010;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float y = 5;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>optional float z = 6;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float z = 6;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>optional float z = 6;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000020;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float z = 6;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000020);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:nhl.containing.networking.protobuf.SimulationItem)
    }

    static {
      defaultInstance = new SimulationItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nhl.containing.networking.protobuf.SimulationItem)
  }

  public interface SimulatorItemListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nhl.containing.networking.protobuf.SimulatorItemList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> 
        getItemsList();
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem getItems(int index);
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    java.util.List<? extends nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code nhl.containing.networking.protobuf.SimulatorItemList}
   */
  public static final class SimulatorItemList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:nhl.containing.networking.protobuf.SimulatorItemList)
      SimulatorItemListOrBuilder {
    // Use SimulatorItemList.newBuilder() to construct.
    private SimulatorItemList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimulatorItemList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimulatorItemList defaultInstance;
    public static SimulatorItemList getDefaultInstance() {
      return defaultInstance;
    }

    public SimulatorItemList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimulatorItemList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulatorItemList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.class, nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.Builder.class);
    }

    public static com.google.protobuf.Parser<SimulatorItemList> PARSER =
        new com.google.protobuf.AbstractParser<SimulatorItemList>() {
      public SimulatorItemList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimulatorItemList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimulatorItemList> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> items_;
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    public java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    public java.util.List<? extends nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
     */
    public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nhl.containing.networking.protobuf.SimulatorItemList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nhl.containing.networking.protobuf.SimulatorItemList)
        nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulatorItemList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.class, nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.Builder.class);
      }

      // Construct using nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nhl.containing.networking.protobuf.SimulationItemProto.internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor;
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList getDefaultInstanceForType() {
        return nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.getDefaultInstance();
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList build() {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList buildPartial() {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList result = new nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList) {
          return mergeFrom((nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList other) {
        if (other == nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nhl.containing.networking.protobuf.SimulationItemProto.SimulatorItemList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder setItems(
          int index, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder setItems(
          int index, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder addItems(nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder addItems(
          int index, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder addItems(
          nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder addItems(
          int index, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public java.util.List<? extends nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.getDefaultInstance());
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.getDefaultInstance());
      }
      /**
       * <code>repeated .nhl.containing.networking.protobuf.SimulationItem items = 1;</code>
       */
      public java.util.List<nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItem.Builder, nhl.containing.networking.protobuf.SimulationItemProto.SimulationItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:nhl.containing.networking.protobuf.SimulatorItemList)
    }

    static {
      defaultInstance = new SimulatorItemList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nhl.containing.networking.protobuf.SimulatorItemList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nhl_containing_networking_protobuf_SimulationItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nhl_containing_networking_protobuf_SimulatorItemList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SimItemProto.proto\022\"nhl.containing.net" +
      "working.protobuf\"\270\003\n\016SimulationItem\022\n\n\002i" +
      "d\030\001 \002(\003\022S\n\004type\030\002 \002(\0162E.nhl.containing.n" +
      "etworking.protobuf.SimulationItem.Simula" +
      "tionItemType\022\020\n\010parentID\030\003 \001(\005\022\t\n\001x\030\004 \001(" +
      "\002\022\t\n\001y\030\005 \001(\002\022\t\n\001z\030\006 \001(\002\"\221\002\n\022SimulationIt" +
      "emType\022\024\n\020PLATFORM_STORAGE\020\000\022\027\n\023PARKINGS" +
      "POT_STORAGE\020\001\022\t\n\005NODES\020\002\022\022\n\016PLATFORM_TRA" +
      "IN\020\003\022\024\n\020PLATFORM_SEASHIP\020\004\022\027\n\023PLATFORM_I" +
      "NLANDSHIP\020\005\022\022\n\016PLATFORM_LORRY\020\006\022\007\n\003AGV\020\007",
      "\022\025\n\021PARKINGSPOT_TRAIN\020\010\022\027\n\023PARKINGSPOT_S" +
      "EASHIP\020\t\022\032\n\026PARKINGSPOT_INLANDSHIP\020\n\022\025\n\021" +
      "PARKINGSPOT_LORRY\020\013\"V\n\021SimulatorItemList" +
      "\022A\n\005items\030\001 \003(\01322.nhl.containing.network" +
      "ing.protobuf.SimulationItemB\025B\023Simulatio" +
      "nItemProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nhl_containing_networking_protobuf_SimulationItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nhl_containing_networking_protobuf_SimulationItem_descriptor,
        new java.lang.String[] { "Id", "Type", "ParentID", "X", "Y", "Z", });
    internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nhl_containing_networking_protobuf_SimulatorItemList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nhl_containing_networking_protobuf_SimulatorItemList_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
