/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_JNI */

#ifndef _Included_controller_JNI
#define _Included_controller_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_JNI
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNI_helloFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
