/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_JNITest */

#ifndef _Included_controller_JNITest
#define _Included_controller_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_JNITest
 * Method:    initPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_initPath
  (JNIEnv *, jclass);

/*
 * Class:     controller_JNITest
 * Method:    getPath
 * Signature: (IIF)[I
 */
JNIEXPORT jintArray JNICALL Java_controller_JNITest_getPath
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     controller_JNITest
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
