/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_JNITest */

#ifndef _Included_controller_JNITest
#define _Included_controller_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_JNITest
 * Method:    initPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_initPath
  (JNIEnv *, jclass);

/*
 * Class:     controller_JNITest
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_helloFromC
  (JNIEnv *, jclass);

/*
 * Class:     controller_JNITest
 * Method:    avgFromC
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_controller_JNITest_avgFromC
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     controller_JNITest
 * Method:    intFromC
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_controller_JNITest_intFromC
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     controller_JNITest
 * Method:    integerFromC
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_controller_JNITest_integerFromC
  (JNIEnv *, jclass, jint);

/*
 * Class:     controller_JNITest
 * Method:    pointInC
 * Signature: (II)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_controller_JNITest_pointInC
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     controller_JNITest
 * Method:    changeNumberInC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_changeNumberInC
  (JNIEnv *, jobject);

/*
 * Class:     controller_JNITest
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_JNITest_cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
